USE a1jbfbsp8uk4jcwc;

INSERT INTO Growers (username, grower_name, license, city, state, email, about, system, strains, cycle, webpage, image)
VALUES 
('budnbloom', 'Bud and Bloom', 'A10-18-0000099-TEMP', 'Santa Ana', 'California', 'BudAndBloomOC@gmail.com', 'Bud and Bloom is the Premier Cannabis Club in Orange County. We are opening soon and Now Hiring!', 'Greenhouse (Indoor Grow Room)', 'Kosher Kush, Blueberry Dome, Jedi Kush, Trainwreck, Sour Tangie, Green Crack', 'Every 90 Days', 'http://budandbloomoc.com/', 'http://budandbloom.sensites.com/wp-content/uploads/sites/134/2016/10/bud-and-bloom-logo.png'),
('cookies_oc', 'Cookies OC', 'A10-17-0000164-TEMP', 'Santa Ana', 'California', 'SNAorders@connectedcannabisco.com', 'Cookies OC is the only grower in Orange County with official Cookies Fam genetics. More than a trendy grower with designer weed, the folks behind Cookies OC continue to develop new genetics with a full spectrum of terpene flavor, lab-tested to ensure potency and quality.', 'Greenhouse (Indoor Grow Room)', 'Gushers, SFV OG, DoSiDos #18, Gelato #41, and Smarties', 'Every 100 Days', 'http://www.connectedcannabisco.com/', 'https://images.weedmaps.com/dispensaries/000/051/778/avatar/square_fill/1510583274-1505865668-450_4050f8a3e9b627c0af6f79946bf66a6213d63164.jpg'),
('supreme_purity', 'Temple of Supreme Purity', 'A10-17-0000111-TEMP', 'Costa Mesa', 'California', 'supremepurity@gmail.com', 'At Temple of Supreme Purity it is our sole purpose to provide our members with the nicest quality of sacrament to achieve desired level of higher consciousness.', 'Greenhouse (Indoor Grow Room)', 'Presidental OG, WiFi OG, Holy Grail OG, Apple Fritter, Tangie, Blue Cheese, Sour Kush', 'Every 66 Days', 'https://weedmaps.com/dispensaries/supreme-purity-2#/details', 'https://images.weedmaps.com/dispensaries/000/053/586/avatar/square_fill/1510583370-1506582753-Neon_Buddah.jpeg');


INSERT INTO Dispensers (username, dispenser_name, license, city, state, email, about, strains_wanted, webpage, image)
VALUES 
('peoples_oc', 'Peoples OC', 'A10-17-0000059-TEMP', 'Santa Ana', 'California', 'INFO@PMCOC.COM', "THE FACILITY ITSELF IS THE BIGGEST OF ITS KIND IN CALIFORNIA, WITH ITS BEAUTIFUL AND SPACIOUS INTERIOR HOUSING A WIDE VARIETY OF CONSUMABLES AND ACCESSORIES, AND STAFFED WITH A PASSIONATE, KNOWLEDGEABLE TEAM READY TO RECOMMEND THE INDUSTRY'S HIGHEST QUALITY MEDICINES.", "Crown OG, Forbidden Fruit", "https://www.peoplesorangecounty.com", "https://static.wixstatic.com/media/604673_e88b0fd6b8d744f48b84e2f90061656d~mv2.png/v1/fill/w_284,h_284,al_c,usm_0.66_1.00_0.01/604673_e88b0fd6b8d744f48b84e2f90061656d~mv2.png" ),
('strainstation', 'Strain Station', 'A10-17-0000087-TEMP', 'Santa Ana', 'California', 'strainstrationoc@gmail.com', "Strain Station is the largest licensed Measure BB Dispensary in Santa Ana. The dispensary staff welcomes recreational cannabis users 21+ and offers a full selection of verified products by Weedmaps’ vendors like Humboldt Apothecary, LOL Edibles, and Kiva.", "Strawberry Banana, Orange Sorbet, Candy Crush, and Oatmeal Cookies", "https://weedmaps.com/dispensaries/15-strain-station#/details", "https://images.weedmaps.com/dispensaries/000/049/097/avatar/square_fill/1510583015-untitled.png" ),
('herboloby35', 'Herbology 35 Cap', 'A10-17-0000333-TEMP', 'Santa Ana', 'California', 'HERBOLOGYSA@GMAIL.COM', "Herbology's promise is to deliver Quality Products, Warm Service, Safety, and Affordability; breaking the industry standards in providing not only the highest caliber of medication, but an impeccably positive and comfortable experience as well.", "Super Cake OG, Gelato, Blue Lightning, OB Niblets, Scooby Snacks", "https://weedmaps.com/dispensaries/house-of-shatter#/details", "https://images.weedmaps.com/dispensaries/000/049/302/avatar/square_fill/1517685717-herb_logo.png" );